per_listener_settings false
listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/runtime/passwords
acl_file /mosquitto/config/acl

persistence true
persistence_location /mosquitto/data/
autosave_interval 30

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true

max_packet_size 8192
max_queued_messages 1000

