[platformio]
default_envs = esp32dev

[env]
test_framework = unity
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -Wall
  -Wextra

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
lib_deps =
  256dpi/MQTT@2.5.2
  bblanchon/ArduinoJson@7.4.1
build_src_filter = +<*>
monitor_speed = 115200

[env:native]
platform = native@1.2.1
build_src_filter = -<*>
test_build_src = false
build_flags =
  ${env.build_flags}
  -DUNIT_TEST

